'use strict'

const COLORS = {
    motion:   { bg:'#4C97FF', dark:'#3373CC' },
    looks:    { bg:'#9966FF', dark:'#7744CC' },
    sound:    { bg:'#CF63CF', dark:'#A94AA9' },
    pen:      { bg:'#59C059', dark:'#3E9E3E' },
    events:   { bg:'#FFAB19', dark:'#CC7A00' },
    control:  { bg:'#FFAB19', dark:'#CC7A00' },
    sensing:  { bg:'#5CB1D6', dark:'#3D8FAD' },
    operator: { bg:'#59C059', dark:'#3E9E3E' },
    variable: { bg:'#FF8C1A', dark:'#CC6600' },
    list:     { bg:'#CC3333', dark:'#992222' },
}

const CATEGORIES = [
    { id:'motion',   label:'Motion'    },
    { id:'looks',    label:'Looks'     },
    { id:'sound',    label:'Sound'     },
    { id:'pen',      label:'Pen'       },
    { id:'events',   label:'Events'    },
    { id:'control',  label:'Control'   },
    { id:'sensing',  label:'Sensing'   },
    { id:'operator', label:'Operators' },
    { id:'variable', label:'Variables' },
    { id:'list',     label:'Lists'     },
]

// Part types:  t = label | input | dropdown | color | slot
// input kinds: k = num | text
// slot kinds:  k = val | bool
const BLOCKS = [
    // ── MOTION ───────────────────────────────────────────────
    { id:'motion_goto', cat:'motion', shape:'stack', parts:[{t:'label',v:'go to'},{t:'dropdown',v:'random position',opts:['random position','last screentap','__sprites__']}] },
    { id:'motion_gotoxy',        cat:'motion', shape:'stack',    parts:[{t:'label',v:'go to x:'},{t:'input',v:'0',k:'num'},{t:'label',v:'y:'},{t:'input',v:'0',k:'num'}] },
    { id:'motion_move',          cat:'motion', shape:'stack',    parts:[{t:'label',v:'move'},{t:'input',v:'10',k:'num'},{t:'label',v:'steps'}] },
    { id:'motion_changex',       cat:'motion', shape:'stack',    parts:[{t:'label',v:'change x by'},{t:'input',v:'10',k:'num'}] },
    { id:'motion_changey',       cat:'motion', shape:'stack',    parts:[{t:'label',v:'change y by'},{t:'input',v:'10',k:'num'}] },
    { id:'motion_setx',          cat:'motion', shape:'stack',    parts:[{t:'label',v:'set x to'},{t:'input',v:'0',k:'num'}] },
    { id:'motion_sety',          cat:'motion', shape:'stack',    parts:[{t:'label',v:'set y to'},{t:'input',v:'0',k:'num'}] },
    { id:'motion_glide',         cat:'motion', shape:'stack',    parts:[{t:'label',v:'glide'},{t:'input',v:'1',k:'num'},{t:'label',v:'secs to x:'},{t:'input',v:'0',k:'num'},{t:'label',v:'y:'},{t:'input',v:'0',k:'num'}] },
    { id:'motion_turnleft',      cat:'motion', shape:'stack',    parts:[{t:'label',v:'turn ↺'},{t:'input',v:'15',k:'num'},{t:'label',v:'degrees'}] },
    { id:'motion_turnright',     cat:'motion', shape:'stack',    parts:[{t:'label',v:'turn ↻'},{t:'input',v:'15',k:'num'},{t:'label',v:'degrees'}] },
    { id:'motion_pointdir',      cat:'motion', shape:'stack',    parts:[{t:'label',v:'point in direction'},{t:'dropdown',v:'90',opts:['0','90','180','270']}] },
    { id:'motion_towards',       cat:'motion', shape:'stack',    parts:[{t:'label',v:'point towards'},{t:'dropdown',v:'sprite',opts:['__sprites__']}] },
    { id:'motion_ifonedge',      cat:'motion', shape:'stack',    parts:[{t:'label',v:'if on edge, bounce'}] },
    { id:'motion_rotstyle',      cat:'motion', shape:'stack',    parts:[{t:'label',v:'set rotation style'},{t:'dropdown',v:'left-right',opts:["left-right","all around","don't rotate"]}] },
    { id:'motion_xpos',          cat:'motion', shape:'reporter', parts:[{t:'label',v:'x position'}] },
    { id:'motion_ypos',          cat:'motion', shape:'reporter', parts:[{t:'label',v:'y position'}] },
    { id:'motion_dir',           cat:'motion', shape:'reporter', parts:[{t:'label',v:'direction'}] },

    // ── LOOKS ────────────────────────────────────────────────
    { id:'looks_say',            cat:'looks', shape:'stack',    parts:[{t:'label',v:'say'},{t:'input',v:'Hello!',k:'text'}] },
    { id:'looks_sayforsecs',     cat:'looks', shape:'stack',    parts:[{t:'label',v:'say'},{t:'input',v:'Hello!',k:'text'},{t:'label',v:'for'},{t:'input',v:'2',k:'num'},{t:'label',v:'secs'}] },
    { id:'looks_think',          cat:'looks', shape:'stack',    parts:[{t:'label',v:'think'},{t:'input',v:'Hmm...',k:'text'}] },
    { id:'looks_thinkforsecs',   cat:'looks', shape:'stack',    parts:[{t:'label',v:'think'},{t:'input',v:'Hmm...',k:'text'},{t:'label',v:'for'},{t:'input',v:'2',k:'num'},{t:'label',v:'secs'}] },
    { id:'looks_show',           cat:'looks', shape:'stack',    parts:[{t:'label',v:'show'}] },
    { id:'looks_hide',           cat:'looks', shape:'stack',    parts:[{t:'label',v:'hide'}] },
    { id:'looks_goback',         cat:'looks', shape:'stack',    parts:[{t:'label',v:'go back'},{t:'input',v:'1',k:'num'},{t:'label',v:'layers'}] },
    { id:'looks_gotofront',      cat:'looks', shape:'stack',    parts:[{t:'label',v:'go to front'}] },
    { id:'looks_changesize',     cat:'looks', shape:'stack',    parts:[{t:'label',v:'change size by'},{t:'input',v:'10',k:'num'}] },
    { id:'looks_setsize',        cat:'looks', shape:'stack',    parts:[{t:'label',v:'set size to'},{t:'input',v:'100',k:'num'},{t:'label',v:'%'}] },
    { id:'looks_nextcostume',    cat:'looks', shape:'stack',    parts:[{t:'label',v:'next costume'}] },
    { id:'looks_switchcostume',  cat:'looks', shape:'stack',    parts:[{t:'label',v:'switch costume to'},{t:'dropdown',v:'costume2',opts:['costume1','costume2']}] },
    { id:'looks_nextbackdrop',   cat:'looks', shape:'stack',    parts:[{t:'label',v:'next backdrop'}] },
    { id:'looks_switchbackdrop', cat:'looks', shape:'stack',    parts:[{t:'label',v:'switch backdrop to'},{t:'dropdown',v:'backdrop1',opts:['__backgrounds__']}] },
    { id:'looks_switchbdwait',   cat:'looks', shape:'stack',    parts:[{t:'label',v:'switch backdrop to'},{t:'dropdown',v:'backdrop1',opts:['__backgrounds__']},{t:'label',v:'and wait'}] },
    { id:'looks_changeeffect',   cat:'looks', shape:'stack',    parts:[{t:'label',v:'change'},{t:'dropdown',v:'color',opts:['color','fisheye','whirl','pixelate','mosaic','brightness','ghost']},{t:'label',v:'effect by'},{t:'input',v:'25',k:'num'}] },
    { id:'looks_seteffect',      cat:'looks', shape:'stack',    parts:[{t:'label',v:'set'},{t:'dropdown',v:'color',opts:['color','fisheye','whirl','pixelate','mosaic','brightness','ghost']},{t:'label',v:'effect to'},{t:'input',v:'0',k:'num'}] },
    { id:'looks_cleareffects',   cat:'looks', shape:'stack',    parts:[{t:'label',v:'clear graphic effects'}] },
    { id:'looks_screenbrightness', cat:'looks', shape:'stack',    parts:[{t:'label',v:'set'},{t:'dropdown',v:'top',opts:['top','bottom']},{t:'label',v:'screen brightness to'},{t:'input',v:'100',k:'num'}] },
    { id:'looks_screenbg',           cat:'looks', shape:'stack',    parts:[{t:'label',v:'set'},{t:'dropdown',v:'top',opts:['top','bottom']},{t:'label',v:'screen background to'},{t:'color',v:'#000000'}] },
    { id:'looks_ledcolor',           cat:'looks', shape:'stack',    parts:[{t:'label',v:'set LED color to'},{t:'color',v:'#ffffff'}] },
    { id:'looks_spritedepth',        cat:'looks', shape:'stack',    parts:[{t:'label',v:'set sprite depth to'},{t:'input',v:'0',k:'num'}] },
    { id:'looks_size',           cat:'looks', shape:'reporter', parts:[{t:'label',v:'size'}] },
    { id:'looks_costumenum',     cat:'looks', shape:'reporter', parts:[{t:'label',v:'costume #'}] },
    { id:'looks_backdropname',   cat:'looks', shape:'reporter', parts:[{t:'label',v:'backdrop name'}] },
    { id:'looks_backdropnum',    cat:'looks', shape:'reporter', parts:[{t:'label',v:'backdrop #'}] },

    // ── SOUND ────────────────────────────────────────────────
    { id:'sound_play',           cat:'sound', shape:'stack',    parts:[{t:'label',v:'play sound'},{t:'dropdown',v:'sound1',opts:['sound1']}] },
    { id:'sound_playuntildone',  cat:'sound', shape:'stack',    parts:[{t:'label',v:'play sound'},{t:'dropdown',v:'sound1',opts:['sound1']},{t:'label',v:'until done'}] },
    { id:'sound_stopall',        cat:'sound', shape:'stack',    parts:[{t:'label',v:'stop all sounds'}] },
    { id:'sound_changevolume',   cat:'sound', shape:'stack',    parts:[{t:'label',v:'change volume by'},{t:'input',v:'-10',k:'num'}] },
    { id:'sound_setvolume',      cat:'sound', shape:'stack',    parts:[{t:'label',v:'set volume to'},{t:'input',v:'100',k:'num'},{t:'label',v:'%'}] },
    { id:'sound_volume',         cat:'sound', shape:'reporter', parts:[{t:'label',v:'volume'}] },

    // ── PEN ──────────────────────────────────────────────────
    { id:'pen_clear',            cat:'pen', shape:'stack',    parts:[{t:'label',v:'clear'}] },
    { id:'pen_up',               cat:'pen', shape:'stack',    parts:[{t:'label',v:'pen up'}] },
    { id:'pen_down',             cat:'pen', shape:'stack',    parts:[{t:'label',v:'pen down'}] },
    { id:'pen_changecolornum',   cat:'pen', shape:'stack',    parts:[{t:'label',v:'change pen color by'},{t:'input',v:'10',k:'num'}] },
    { id:'pen_setcolornum',      cat:'pen', shape:'stack',    parts:[{t:'label',v:'set pen color to'},{t:'input',v:'0',k:'num'}] },
    { id:'pen_setcolorpick',     cat:'pen', shape:'stack',    parts:[{t:'label',v:'set pen color to'},{t:'color',v:'#ff0000'}] },
    { id:'pen_changesize',       cat:'pen', shape:'stack',    parts:[{t:'label',v:'change pen size by'},{t:'input',v:'1',k:'num'}] },
    { id:'pen_setsize',          cat:'pen', shape:'stack',    parts:[{t:'label',v:'set pen size to'},{t:'input',v:'1',k:'num'}] },
    { id:'pen_changeshade',      cat:'pen', shape:'stack',    parts:[{t:'label',v:'change pen shade by'},{t:'input',v:'10',k:'num'}] },
    { id:'pen_setshade',         cat:'pen', shape:'stack',    parts:[{t:'label',v:'set pen shade to'},{t:'input',v:'50',k:'num'}] },
    { id:'pen_stamp',            cat:'pen', shape:'stack',    parts:[{t:'label',v:'stamp'}] },

    // ── EVENTS ───────────────────────────────────────────────
    { id:'event_start',          cat:'events', shape:'hat',   parts:[{t:'label',v:'▶ on start'}] },
    { id:'event_keypressed',     cat:'events', shape:'hat',   parts:[{t:'label',v:'when'},{t:'dropdown',v:'A',opts:['any key','A','B','X','Y','L','R','ZL','ZR','Up','Down','Left','Right','Start','Select']},{t:'label',v:'pressed'}] },
    { id:'event_tapped',         cat:'events', shape:'hat',   parts:[{t:'label',v:'when this sprite tapped'}] },
    { id:'event_receive',        cat:'events', shape:'hat',   parts:[{t:'label',v:'when I receive'},{t:'dropdown',v:'new message',opts:['__messages__']}] },
    { id:'event_backdropswitch', cat:'events', shape:'hat',   parts:[{t:'label',v:'when backdrop switches to'},{t:'dropdown',v:'backdrop1',opts:['__backgrounds__']}] },
    { id:'event_loudness',       cat:'events', shape:'hat',   parts:[{t:'label',v:'when'},{t:'dropdown',v:'loudness',opts:['loudness','timer']},{t:'label',v:'>'},{t:'input',v:'10',k:'num'}] },
    { id:'event_broadcast',      cat:'events', shape:'stack', parts:[{t:'label',v:'broadcast'},{t:'dropdown',v:'new message',opts:['__messages__']}] },
    { id:'event_broadcastwait',  cat:'events', shape:'stack', parts:[{t:'label',v:'broadcast'},{t:'dropdown',v:'new message',opts:['__messages__']},{t:'label',v:'and wait'}] },

    // ── CONTROL ──────────────────────────────────────────────
    { id:'control_wait',         cat:'control', shape:'stack',  parts:[{t:'label',v:'wait'},{t:'input',v:'1',k:'num'},{t:'label',v:'secs'}] },
    { id:'control_waituntil',    cat:'control', shape:'stack',  parts:[{t:'label',v:'wait until'},{t:'slot',k:'bool'}] },
    { id:'control_repeat',       cat:'control', shape:'cblock', parts:[{t:'label',v:'repeat'},{t:'input',v:'10',k:'num'}] },
    { id:'control_forever',      cat:'control', shape:'cblock', parts:[{t:'label',v:'forever'}] },
    { id:'control_if',           cat:'control', shape:'cblock', parts:[{t:'label',v:'if'},{t:'slot',k:'bool'},{t:'label',v:'then'}] },
    { id:'control_ifelse',       cat:'control', shape:'cblock', parts:[{t:'label',v:'if'},{t:'slot',k:'bool'},{t:'label',v:'then / else'}] },
    { id:'control_repeatuntil',  cat:'control', shape:'cblock', parts:[{t:'label',v:'repeat until'},{t:'slot',k:'bool'}] },
    { id:'control_stop',         cat:'control', shape:'cap',    parts:[{t:'label',v:'stop'},{t:'dropdown',v:'all',opts:['all','this script','other scripts in sprite']}] },
    { id:'control_startclone',   cat:'control', shape:'hat',    parts:[{t:'label',v:'when I start as a clone'}] },
    { id:'control_createclone',  cat:'control', shape:'stack',  parts:[{t:'label',v:'create clone of'},{t:'dropdown',v:'myself',opts:['myself','__sprites__']}] },
    { id:'control_deleteclone',  cat:'control', shape:'stack',  parts:[{t:'label',v:'delete this clone'}] },

    // ── SENSING ──────────────────────────────────────────────
    { id:'sensing_ask',          cat:'sensing', shape:'stack',   parts:[{t:'label',v:'ask'},{t:'input',v:"What's your name?",k:'text'},{t:'label',v:'and wait'}] },
    { id:'sensing_answer',       cat:'sensing', shape:'reporter',parts:[{t:'label',v:'answer'}] },
    { id:'sensing_keypressed',   cat:'sensing', shape:'boolean', parts:[{t:'label',v:'key'},{t:'dropdown',v:'A',opts:['any key','A','B','X','Y','L','R','ZL','ZR','Up','Down','Left','Right','Start','Select']},{t:'label',v:'pressed?'}] },
    { id:'sensing_screentapped', cat:'sensing', shape:'boolean', parts:[{t:'label',v:'screen tapped?'}] },
    { id:'sensing_distanceto',   cat:'sensing', shape:'reporter',parts:[{t:'label',v:'distance to'},{t:'dropdown',v:'sprite',opts:['__sprites__']}] },
    { id:'sensing_touching',     cat:'sensing', shape:'boolean', parts:[{t:'label',v:'touching'},{t:'dropdown',v:'sprite',opts:['__sprites__','edge of stage']},{t:'label',v:'?'}] },
    { id:'sensing_touchcolor',   cat:'sensing', shape:'boolean', parts:[{t:'label',v:'touching color'},{t:'color',v:'#0000ff'},{t:'label',v:'?'}] },
    { id:'sensing_colortouch',   cat:'sensing', shape:'boolean', parts:[{t:'label',v:'color'},{t:'color',v:'#ff0000'},{t:'label',v:'is touching'},{t:'color',v:'#0000ff'},{t:'label',v:'?'}] },
    { id:'sensing_loudness',     cat:'sensing', shape:'reporter',parts:[{t:'label',v:'loudness'}] },
    { id:'sensing_attribof',     cat:'sensing', shape:'reporter',parts:[{t:'dropdown',v:'x position',opts:['x position','y position','direction','costume #','costume name','size','volume']},{t:'label',v:'of'},{t:'dropdown',v:'sprite',opts:['__sprites__']}] },
    { id:'sensing_current',      cat:'sensing', shape:'reporter',parts:[{t:'label',v:'current'},{t:'dropdown',v:'minute',opts:['year','month','date','day of week','hour','minute','second']}] },
    { id:'sensing_starttimer',   cat:'sensing', shape:'stack',   parts:[{t:'label',v:'start timer'}] },
    { id:'sensing_resettimer',   cat:'sensing', shape:'stack',   parts:[{t:'label',v:'reset timer'}] },
    { id:'sensing_timer',        cat:'sensing', shape:'reporter',parts:[{t:'label',v:'timer'}] },
    { id:'sensing_circlepadx',   cat:'sensing', shape:'reporter',parts:[{t:'label',v:'circle pad x'}] },
    { id:'sensing_circlepady',   cat:'sensing', shape:'reporter',parts:[{t:'label',v:'circle pad y'}] },
    { id:'sensing_cstickx',      cat:'sensing', shape:'reporter',parts:[{t:'label',v:'c-stick x'}] },
    { id:'sensing_csticky',      cat:'sensing', shape:'reporter',parts:[{t:'label',v:'c-stick y'}] },
    { id:'sensing_gyrox',        cat:'sensing', shape:'reporter',parts:[{t:'label',v:'gyroscope x'}] },
    { id:'sensing_gyroy',        cat:'sensing', shape:'reporter',parts:[{t:'label',v:'gyroscope y'}] },
    { id:'sensing_gyroz',        cat:'sensing', shape:'reporter',parts:[{t:'label',v:'gyroscope z'}] },
    { id:'sensing_accelx',       cat:'sensing', shape:'reporter',parts:[{t:'label',v:'accelerometer x'}] },
    { id:'sensing_accely',       cat:'sensing', shape:'reporter',parts:[{t:'label',v:'accelerometer y'}] },
    { id:'sensing_accelz',       cat:'sensing', shape:'reporter',parts:[{t:'label',v:'accelerometer z'}] },
    { id:'sensing_islidopen',    cat:'sensing', shape:'boolean', parts:[{t:'label',v:'is lid open?'}] },
    { id:'sensing_battery',      cat:'sensing', shape:'reporter',parts:[{t:'label',v:'battery level'}] },
    { id:'sensing_ischarging',   cat:'sensing', shape:'boolean', parts:[{t:'label',v:'is charging?'}] },
    { id:'sensing_3dslider',     cat:'sensing', shape:'reporter',parts:[{t:'label',v:'3D slider value'}] },
    { id:'sensing_turnvideo',    cat:'sensing', shape:'stack',   parts:[{t:'label',v:'turn video'},{t:'dropdown',v:'off',opts:['on','off']}] },
    { id:'sensing_videotrans',   cat:'sensing', shape:'stack',   parts:[{t:'label',v:'set video transparency to'},{t:'input',v:'50',k:'num'},{t:'label',v:'%'}] },
    { id:'sensing_videomotion',  cat:'sensing', shape:'reporter',parts:[{t:'label',v:'video'},{t:'dropdown',v:'motion',opts:['motion','direction']}] },

    // ── OPERATORS ────────────────────────────────────────────
    { id:'op_add',               cat:'operator', shape:'reporter',parts:[{t:'slot',k:'val'},{t:'label',v:'+'},{t:'slot',k:'val'}] },
    { id:'op_sub',               cat:'operator', shape:'reporter',parts:[{t:'slot',k:'val'},{t:'label',v:'-'},{t:'slot',k:'val'}] },
    { id:'op_mul',               cat:'operator', shape:'reporter',parts:[{t:'slot',k:'val'},{t:'label',v:'*'},{t:'slot',k:'val'}] },
    { id:'op_div',               cat:'operator', shape:'reporter',parts:[{t:'slot',k:'val'},{t:'label',v:'/'},{t:'slot',k:'val'}] },
    { id:'op_mod',               cat:'operator', shape:'reporter',parts:[{t:'slot',k:'val'},{t:'label',v:'mod'},{t:'slot',k:'val'}] },
    { id:'op_round',             cat:'operator', shape:'reporter',parts:[{t:'label',v:'round'},{t:'slot',k:'val'}] },
    { id:'op_math',              cat:'operator', shape:'reporter',parts:[{t:'dropdown',v:'sqrt',opts:['abs','sqrt','sin','cos','tan','asin','acos','atan','ln','log','e^','10^']},{t:'label',v:'of'},{t:'input',v:'9',k:'num'}] },
    { id:'op_lt',                cat:'operator', shape:'boolean', parts:[{t:'slot',k:'val'},{t:'label',v:'<'},{t:'slot',k:'val'}] },
    { id:'op_eq',                cat:'operator', shape:'boolean', parts:[{t:'slot',k:'val'},{t:'label',v:'='},{t:'slot',k:'val'}] },
    { id:'op_gt',                cat:'operator', shape:'boolean', parts:[{t:'slot',k:'val'},{t:'label',v:'>'},{t:'slot',k:'val'}] },
    { id:'op_and',               cat:'operator', shape:'boolean', parts:[{t:'slot',k:'bool'},{t:'label',v:'and'},{t:'slot',k:'bool'}] },
    { id:'op_or',                cat:'operator', shape:'boolean', parts:[{t:'slot',k:'bool'},{t:'label',v:'or'},{t:'slot',k:'bool'}] },
    { id:'op_not',               cat:'operator', shape:'boolean', parts:[{t:'label',v:'not'},{t:'slot',k:'bool'}] },
    { id:'op_join',              cat:'operator', shape:'reporter',parts:[{t:'label',v:'join'},{t:'input',v:'hello',k:'text'},{t:'input',v:'world',k:'text'}] },
    { id:'op_length',            cat:'operator', shape:'reporter',parts:[{t:'label',v:'length of'},{t:'input',v:'world',k:'text'}] },
    { id:'op_letter',            cat:'operator', shape:'reporter',parts:[{t:'label',v:'letter'},{t:'input',v:'1',k:'num'},{t:'label',v:'of'},{t:'input',v:'world',k:'text'}] },
    { id:'op_contains',          cat:'operator', shape:'boolean', parts:[{t:'slot',k:'val'},{t:'label',v:'contains'},{t:'slot',k:'val'},{t:'label',v:'?'}] },

    // ── VARIABLES ────────────────────────────────────────────
    { id:'var_value',            cat:'variable', shape:'reporter',parts:[{t:'label',v:'variable'}] },
    { id:'var_set',              cat:'variable', shape:'stack',   parts:[{t:'label',v:'set'},{t:'dropdown',v:'var',opts:['__vars__']},{t:'label',v:'to'},{t:'slot',k:'val'}] },
    { id:'var_change',           cat:'variable', shape:'stack',   parts:[{t:'label',v:'change'},{t:'dropdown',v:'var',opts:['__vars__']},{t:'label',v:'by'},{t:'slot',k:'val'}] },
    { id:'var_show',             cat:'variable', shape:'stack',   parts:[{t:'label',v:'show variable'},{t:'dropdown',v:'var',opts:['__vars__']}] },
    { id:'var_hide',             cat:'variable', shape:'stack',   parts:[{t:'label',v:'hide variable'},{t:'dropdown',v:'var',opts:['__vars__']}] },

    // ── LISTS ────────────────────────────────────────────────
    { id:'list_value',           cat:'list', shape:'reporter',parts:[{t:'label',v:'list'}] },
    { id:'list_add',             cat:'list', shape:'stack',   parts:[{t:'label',v:'add'},{t:'slot',k:'val'},{t:'label',v:'to'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_delete',          cat:'list', shape:'stack',   parts:[{t:'label',v:'delete'},{t:'input',v:'1',k:'num'},{t:'label',v:'of'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_deleteall',       cat:'list', shape:'stack',   parts:[{t:'label',v:'delete all of'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_insert',          cat:'list', shape:'stack',   parts:[{t:'label',v:'insert'},{t:'slot',k:'val'},{t:'label',v:'at'},{t:'input',v:'1',k:'num'},{t:'label',v:'of'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_replace',         cat:'list', shape:'stack',   parts:[{t:'label',v:'replace item'},{t:'input',v:'1',k:'num'},{t:'label',v:'of'},{t:'dropdown',v:'list',opts:['__lists__']},{t:'label',v:'with'},{t:'slot',k:'val'}] },
    { id:'list_item',            cat:'list', shape:'reporter',parts:[{t:'label',v:'item'},{t:'input',v:'1',k:'num'},{t:'label',v:'of'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_itemnum',         cat:'list', shape:'reporter',parts:[{t:'label',v:'item # of'},{t:'slot',k:'val'},{t:'label',v:'in'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_length',          cat:'list', shape:'reporter',parts:[{t:'label',v:'length of'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_contains',        cat:'list', shape:'boolean', parts:[{t:'dropdown',v:'list',opts:['__lists__']},{t:'label',v:'contains'},{t:'slot',k:'val'},{t:'label',v:'?'}] },
    { id:'list_show',            cat:'list', shape:'stack',   parts:[{t:'label',v:'show list'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_hide',            cat:'list', shape:'stack',   parts:[{t:'label',v:'hide list'},{t:'dropdown',v:'list',opts:['__lists__']}] },
    { id:'list_setlength',       cat:'list', shape:'stack',   parts:[{t:'label',v:'set length of'},{t:'dropdown',v:'list',opts:['__lists__']},{t:'label',v:'to'},{t:'input',v:'0',k:'num'}] },
]
